- hosts: localhost
  become: true
  tasks:
    - name: Install required packages.
      tags: pkgs
      ansible.builtin.package:
        name: 
          - httpd
          - firewalld

    - name: Start services.
      tags: services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld

    - name: Check to see if there is already an index.html file.
      tags: index
      ansible.builtin.stat:
        path: /var/www/html/index.html
      register: index

    - name: Create custom index page.
      tags: index
      ansible.builtin.copy:
        src: ./files/index.html
        dest: /var/www/html/index.html
      when: not index.stat.exists

    - name: Allow http (80/tcp) traffic through the firewall.
      tags: firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true 
