- hosts: localhost
  become: true
  tasks:
    - name: Install required packages.
      tags: pkgs
      ansible.builtin.package:
        name: 
          - httpd
          - firewalld

    - name: Start services.
      tags: services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld

    - name: Create custom index page.
      tags: index
      ansible.builtin.template:
        src: ./templates/index.html.j2
        dest: /var/www/html/index.html

    - name: Allow http (80/tcp) traffic through the firewall.
      tags: firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true 
